AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MyKeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: 'Select the key'
  MyEnvironmentName:
    Type: 'String'
    Description: 'select the environment'
    Default: Prod
    AllowedValues:
      - Prod
      - Dev  
Mappings:
  MyRegionMap:
    ap-south-1:
      HVM64: ami-02913db388613c3e1
    us-east-2:
      HVM64: ami-0c64dd618a49aeee8
  MyEnvironmentMap:
    Prod:
      instanceType: t2.small
    Dev:
      instanceType: t2.micro         
Resources:
  MyVMInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref MyEnvironmentName
        - instanceType
      KeyName: !Ref MyKeyName
  MyElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref MyVMInstance
