AWSTemplateFormatVersion: 2010-09-09
Description: Parameter Key Type Demo

Parameters:
  MyKeyName:
    Description: select the keypair
    Type: 'AWS::EC2::KeyPair::KeyName'

Resources:
  ProdEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02913db388613c3e1
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: ssh awengers
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'  
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
      