AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance

Resources:
  ProdEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-02913db388613c3e1
      InstanceType: t2.micro
      KeyName: mano-key-1
      SecurityGroups:
        - default