AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance

Resources:
  ProdEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-02913db388613c3e1
      InstanceType: t2.micro
      KeyName: mano-key-1
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: my new SSH SG
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0  
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0 
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIP: 0.0.0.0/0       
  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref ProdEC2Instance     