AWSTemplateFormatVersion: 2010-09-09
Resources:
  DevEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0a74bfeb190bd404f
      InstanceType: t2.micro
      KeyName: mano-key-2