AWSTemplateFormatVersion: 2010-09-09
Description: outputs practices

Parameters:
  MyKeyName:
    Description: 'Select the keyName' 
    Type: 'AWS::EC2::KeyPair::KeyName'
  MyEnvironmentName:
    Description: 'Select the Environment'
    Type: 'String'
    Default: Dev
    AllowedValues:
      - Prod
      - Dev
    ConstraintDescription: must be development or production
Mappings:
  MyRegionMap:
    ap-south-1:
      HVM64: ami-02913db388613c3e1
    us-east-2:
      HVM64: ami-0c64dd618a49aeee8
  MyEnvironmentMap:
    Prod:
      instanceType: t2.micro
    Dev:
      instanceType: t2.small  
Resources:
  MyVMInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      KeyName: !Ref MyKeyName
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref MyEnvironmentName
        - instanceType
      SecurityGroups:
        - !ImportValue DevGlobalssh
      AvailabilityZone: !ImportValue Stacl1-InstanceAZ  