AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyKeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: 'Select The key'
Mappings:
  MyRegionMap:
    ap-south-1:
      HVM64: ami-02913db388613c3e1
    us-east-2:
      HVM64: ami-0c64dd618a49aeee8


Resources:
  MyVmInstance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName